var SWFUpload;SWFUpload==void 0&&(SWFUpload=function(a){this.initSWFUpload(a)});SWFUpload.prototype.initSWFUpload=function(a){try{this.customSettings={},this.settings=a,this.eventQueue=[],this.movieName="SWFUpload_"+SWFUpload.movieCount++,this.movieElement=null,SWFUpload.instances[this.movieName]=this,this.initSettings(),this.loadFlash(),this.displayDebugInfo()}catch(b){throw delete SWFUpload.instances[this.movieName],b;}};SWFUpload.instances={};SWFUpload.movieCount=0;SWFUpload.version="2.2.0 2009-03-25";
SWFUpload.QUEUE_ERROR={QUEUE_LIMIT_EXCEEDED:-100,FILE_EXCEEDS_SIZE_LIMIT:-110,ZERO_BYTE_FILE:-120,INVALID_FILETYPE:-130};SWFUpload.UPLOAD_ERROR={HTTP_ERROR:-200,MISSING_UPLOAD_URL:-210,IO_ERROR:-220,SECURITY_ERROR:-230,UPLOAD_LIMIT_EXCEEDED:-240,UPLOAD_FAILED:-250,SPECIFIED_FILE_ID_NOT_FOUND:-260,FILE_VALIDATION_FAILED:-270,FILE_CANCELLED:-280,UPLOAD_STOPPED:-290};SWFUpload.FILE_STATUS={QUEUED:-1,IN_PROGRESS:-2,ERROR:-3,COMPLETE:-4,CANCELLED:-5};
SWFUpload.BUTTON_ACTION={SELECT_FILE:-100,SELECT_FILES:-110,START_UPLOAD:-120};SWFUpload.CURSOR={ARROW:-1,HAND:-2};SWFUpload.WINDOW_MODE={WINDOW:"window",TRANSPARENT:"transparent",OPAQUE:"opaque"};SWFUpload.completeURL=function(a){if(typeof a!=="string"||a.match(/^https?:\/\//i)||a.match(/^\//))return a;var b=window.location.pathname.lastIndexOf("/");path=b<=0?"/":window.location.pathname.substr(0,b)+"/";return path+a};
SWFUpload.prototype.initSettings=function(){this.ensureDefault=function(a,b){this.settings[a]=this.settings[a]==void 0?b:this.settings[a]};this.ensureDefault("upload_url","");this.ensureDefault("preserve_relative_urls",!1);this.ensureDefault("file_post_name","Filedata");this.ensureDefault("post_params",{});this.ensureDefault("use_query_string",!1);this.ensureDefault("requeue_on_error",!1);this.ensureDefault("http_success",[]);this.ensureDefault("assume_success_timeout",0);this.ensureDefault("file_types",
"*.*");this.ensureDefault("file_types_description","All Files");this.ensureDefault("file_size_limit",0);this.ensureDefault("file_upload_limit",0);this.ensureDefault("file_queue_limit",0);this.ensureDefault("flash_url","swfupload.swf");this.ensureDefault("prevent_swf_caching",!0);this.ensureDefault("button_image_url","");this.ensureDefault("button_width",1);this.ensureDefault("button_height",1);this.ensureDefault("button_text","");this.ensureDefault("button_text_style","color: #000000; font-size: 16pt;");
this.ensureDefault("button_text_top_padding",0);this.ensureDefault("button_text_left_padding",0);this.ensureDefault("button_action",SWFUpload.BUTTON_ACTION.SELECT_FILES);this.ensureDefault("button_disabled",!1);this.ensureDefault("button_placeholder_id","");this.ensureDefault("button_placeholder",null);this.ensureDefault("button_cursor",SWFUpload.CURSOR.ARROW);this.ensureDefault("button_window_mode",SWFUpload.WINDOW_MODE.WINDOW);this.ensureDefault("debug",!1);this.settings.debug_enabled=this.settings.debug;
this.settings.return_upload_start_handler=this.returnUploadStart;this.ensureDefault("swfupload_loaded_handler",null);this.ensureDefault("file_dialog_start_handler",null);this.ensureDefault("file_queued_handler",null);this.ensureDefault("file_queue_error_handler",null);this.ensureDefault("file_dialog_complete_handler",null);this.ensureDefault("upload_start_handler",null);this.ensureDefault("upload_progress_handler",null);this.ensureDefault("upload_error_handler",null);this.ensureDefault("upload_success_handler",
null);this.ensureDefault("upload_complete_handler",null);this.ensureDefault("debug_handler",this.debugMessage);this.ensureDefault("custom_settings",{});this.customSettings=this.settings.custom_settings;if(this.settings.prevent_swf_caching)this.settings.flash_url=this.settings.flash_url+(this.settings.flash_url.indexOf("?")<0?"?":"&")+"preventswfcaching="+(new Date).getTime();if(!this.settings.preserve_relative_urls)this.settings.upload_url=SWFUpload.completeURL(this.settings.upload_url),this.settings.button_image_url=
SWFUpload.completeURL(this.settings.button_image_url);delete this.ensureDefault};
SWFUpload.prototype.loadFlash=function(){var a,b;if(document.getElementById(this.movieName)!==null)throw"ID "+this.movieName+" is already in use. The Flash Object could not be added";a=document.getElementById(this.settings.button_placeholder_id)||this.settings.button_placeholder;if(a==void 0)throw"Could not find the placeholder element: "+this.settings.button_placeholder_id;b=document.createElement("div");b.innerHTML=this.getFlashHTML();a.parentNode.replaceChild(b.firstChild,a);window[this.movieName]==
void 0&&(window[this.movieName]=this.getMovieElement())};
SWFUpload.prototype.getFlashHTML=function(){return['<object id="',this.movieName,'" type="application/x-shockwave-flash" data="',this.settings.flash_url,'" width="',this.settings.button_width,'" height="',this.settings.button_height,'" class="swfupload"><param name="wmode" value="',this.settings.button_window_mode,'" /><param name="movie" value="',this.settings.flash_url,'" /><param name="quality" value="high" /><param name="menu" value="false" /><param name="allowScriptAccess" value="always" />','<param name="flashvars" value="'+
this.getFlashVars()+'" />',"</object>"].join("")};
SWFUpload.prototype.getFlashVars=function(){var a=this.buildParamString(),b=this.settings.http_success.join(",");return["movieName=",encodeURIComponent(this.movieName),"&amp;uploadURL=",encodeURIComponent(this.settings.upload_url),"&amp;useQueryString=",encodeURIComponent(this.settings.use_query_string),"&amp;requeueOnError=",encodeURIComponent(this.settings.requeue_on_error),"&amp;httpSuccess=",encodeURIComponent(b),"&amp;assumeSuccessTimeout=",encodeURIComponent(this.settings.assume_success_timeout),"&amp;params=",
encodeURIComponent(a),"&amp;filePostName=",encodeURIComponent(this.settings.file_post_name),"&amp;fileTypes=",encodeURIComponent(this.settings.file_types),"&amp;fileTypesDescription=",encodeURIComponent(this.settings.file_types_description),"&amp;fileSizeLimit=",encodeURIComponent(this.settings.file_size_limit),"&amp;fileUploadLimit=",encodeURIComponent(this.settings.file_upload_limit),"&amp;fileQueueLimit=",encodeURIComponent(this.settings.file_queue_limit),"&amp;debugEnabled=",encodeURIComponent(this.settings.debug_enabled),
"&amp;buttonImageURL=",encodeURIComponent(this.settings.button_image_url),"&amp;buttonWidth=",encodeURIComponent(this.settings.button_width),"&amp;buttonHeight=",encodeURIComponent(this.settings.button_height),"&amp;buttonText=",encodeURIComponent(this.settings.button_text),"&amp;buttonTextTopPadding=",encodeURIComponent(this.settings.button_text_top_padding),"&amp;buttonTextLeftPadding=",encodeURIComponent(this.settings.button_text_left_padding),"&amp;buttonTextStyle=",encodeURIComponent(this.settings.button_text_style),
"&amp;buttonAction=",encodeURIComponent(this.settings.button_action),"&amp;buttonDisabled=",encodeURIComponent(this.settings.button_disabled),"&amp;buttonCursor=",encodeURIComponent(this.settings.button_cursor)].join("")};SWFUpload.prototype.getMovieElement=function(){if(this.movieElement==void 0)this.movieElement=document.getElementById(this.movieName);if(this.movieElement===null)throw"Could not find Flash element";return this.movieElement};
SWFUpload.prototype.buildParamString=function(){var a=this.settings.post_params,b=[];if(typeof a==="object")for(var c in a)a.hasOwnProperty(c)&&b.push(encodeURIComponent(c.toString())+"="+encodeURIComponent(a[c].toString()));return b.join("&amp;")};
SWFUpload.prototype.destroy=function(){try{this.cancelUpload(null,!1);var a=null;if((a=this.getMovieElement())&&typeof a.CallFunction==="unknown"){for(var b in a)try{typeof a[b]==="function"&&(a[b]=null)}catch(c){}try{a.parentNode.removeChild(a)}catch(d){}}window[this.movieName]=null;SWFUpload.instances[this.movieName]=null;delete SWFUpload.instances[this.movieName];this.movieName=this.eventQueue=this.customSettings=this.settings=this.movieElement=null;return!0}catch(e){return!1}};
SWFUpload.prototype.displayDebugInfo=function(){this.debug(["---SWFUpload Instance Info---\nVersion: ",SWFUpload.version,"\nMovie Name: ",this.movieName,"\nSettings:\n\tupload_url:               ",this.settings.upload_url,"\n\tflash_url:                ",this.settings.flash_url,"\n\tuse_query_string:         ",this.settings.use_query_string.toString(),"\n\trequeue_on_error:         ",this.settings.requeue_on_error.toString(),"\n\thttp_success:             ",this.settings.http_success.join(", "),"\n\tassume_success_timeout:   ",
this.settings.assume_success_timeout,"\n\tfile_post_name:           ",this.settings.file_post_name,"\n\tpost_params:              ",this.settings.post_params.toString(),"\n\tfile_types:               ",this.settings.file_types,"\n\tfile_types_description:   ",this.settings.file_types_description,"\n\tfile_size_limit:          ",this.settings.file_size_limit,"\n\tfile_upload_limit:        ",this.settings.file_upload_limit,"\n\tfile_queue_limit:         ",this.settings.file_queue_limit,"\n\tdebug:                    ",
this.settings.debug.toString(),"\n\tprevent_swf_caching:      ",this.settings.prevent_swf_caching.toString(),"\n\tbutton_placeholder_id:    ",this.settings.button_placeholder_id.toString(),"\n\tbutton_placeholder:       ",this.settings.button_placeholder?"Set":"Not Set","\n\tbutton_image_url:         ",this.settings.button_image_url.toString(),"\n\tbutton_width:             ",this.settings.button_width.toString(),"\n\tbutton_height:            ",this.settings.button_height.toString(),"\n\tbutton_text:              ",
this.settings.button_text.toString(),"\n\tbutton_text_style:        ",this.settings.button_text_style.toString(),"\n\tbutton_text_top_padding:  ",this.settings.button_text_top_padding.toString(),"\n\tbutton_text_left_padding: ",this.settings.button_text_left_padding.toString(),"\n\tbutton_action:            ",this.settings.button_action.toString(),"\n\tbutton_disabled:          ",this.settings.button_disabled.toString(),"\n\tcustom_settings:          ",this.settings.custom_settings.toString(),"\nEvent Handlers:\n\tswfupload_loaded_handler assigned:  ",
(typeof this.settings.swfupload_loaded_handler==="function").toString(),"\n\tfile_dialog_start_handler assigned: ",(typeof this.settings.file_dialog_start_handler==="function").toString(),"\n\tfile_queued_handler assigned:       ",(typeof this.settings.file_queued_handler==="function").toString(),"\n\tfile_queue_error_handler assigned:  ",(typeof this.settings.file_queue_error_handler==="function").toString(),"\n\tupload_start_handler assigned:      ",(typeof this.settings.upload_start_handler===
"function").toString(),"\n\tupload_progress_handler assigned:   ",(typeof this.settings.upload_progress_handler==="function").toString(),"\n\tupload_error_handler assigned:      ",(typeof this.settings.upload_error_handler==="function").toString(),"\n\tupload_success_handler assigned:    ",(typeof this.settings.upload_success_handler==="function").toString(),"\n\tupload_complete_handler assigned:   ",(typeof this.settings.upload_complete_handler==="function").toString(),"\n\tdebug_handler assigned:             ",
(typeof this.settings.debug_handler==="function").toString(),"\n"].join(""))};SWFUpload.prototype.addSetting=function(a,b,c){return b==void 0?this.settings[a]=c:this.settings[a]=b};SWFUpload.prototype.getSetting=function(a){if(this.settings[a]!=void 0)return this.settings[a];return""};
SWFUpload.prototype.callFlash=function(a,b){b=b||[];var c=this.getMovieElement(),d,e;try{e=c.CallFunction('<invoke name="'+a+'" returntype="javascript">'+__flash__argumentsToXML(b,0)+"</invoke>"),d=eval(e)}catch(f){throw"Call to "+a+" failed";}d!=void 0&&typeof d.post==="object"&&(d=this.unescapeFilePostParams(d));return d};SWFUpload.prototype.selectFile=function(){this.callFlash("SelectFile")};SWFUpload.prototype.selectFiles=function(){this.callFlash("SelectFiles")};
SWFUpload.prototype.startUpload=function(a){this.callFlash("StartUpload",[a])};SWFUpload.prototype.cancelUpload=function(a,b){b!==!1&&(b=!0);this.callFlash("CancelUpload",[a,b])};SWFUpload.prototype.stopUpload=function(){this.callFlash("StopUpload")};SWFUpload.prototype.getStats=function(){return this.callFlash("GetStats")};SWFUpload.prototype.setStats=function(a){this.callFlash("SetStats",[a])};
SWFUpload.prototype.getFile=function(a){return typeof a==="number"?this.callFlash("GetFileByIndex",[a]):this.callFlash("GetFile",[a])};SWFUpload.prototype.addFileParam=function(a,b,c){return this.callFlash("AddFileParam",[a,b,c])};SWFUpload.prototype.removeFileParam=function(a,b){this.callFlash("RemoveFileParam",[a,b])};SWFUpload.prototype.setUploadURL=function(a){this.settings.upload_url=a.toString();this.callFlash("SetUploadURL",[a])};
SWFUpload.prototype.setPostParams=function(a){this.settings.post_params=a;this.callFlash("SetPostParams",[a])};SWFUpload.prototype.addPostParam=function(a,b){this.settings.post_params[a]=b;this.callFlash("SetPostParams",[this.settings.post_params])};SWFUpload.prototype.removePostParam=function(a){delete this.settings.post_params[a];this.callFlash("SetPostParams",[this.settings.post_params])};
SWFUpload.prototype.setFileTypes=function(a,b){this.settings.file_types=a;this.settings.file_types_description=b;this.callFlash("SetFileTypes",[a,b])};SWFUpload.prototype.setFileSizeLimit=function(a){this.settings.file_size_limit=a;this.callFlash("SetFileSizeLimit",[a])};SWFUpload.prototype.setFileUploadLimit=function(a){this.settings.file_upload_limit=a;this.callFlash("SetFileUploadLimit",[a])};
SWFUpload.prototype.setFileQueueLimit=function(a){this.settings.file_queue_limit=a;this.callFlash("SetFileQueueLimit",[a])};SWFUpload.prototype.setFilePostName=function(a){this.settings.file_post_name=a;this.callFlash("SetFilePostName",[a])};SWFUpload.prototype.setUseQueryString=function(a){this.settings.use_query_string=a;this.callFlash("SetUseQueryString",[a])};SWFUpload.prototype.setRequeueOnError=function(a){this.settings.requeue_on_error=a;this.callFlash("SetRequeueOnError",[a])};
SWFUpload.prototype.setHTTPSuccess=function(a){typeof a==="string"&&(a=a.replace(" ","").split(","));this.settings.http_success=a;this.callFlash("SetHTTPSuccess",[a])};SWFUpload.prototype.setAssumeSuccessTimeout=function(a){this.settings.assume_success_timeout=a;this.callFlash("SetAssumeSuccessTimeout",[a])};SWFUpload.prototype.setDebugEnabled=function(a){this.settings.debug_enabled=a;this.callFlash("SetDebugEnabled",[a])};
SWFUpload.prototype.setButtonImageURL=function(a){a==void 0&&(a="");this.settings.button_image_url=a;this.callFlash("SetButtonImageURL",[a])};SWFUpload.prototype.setButtonDimensions=function(a,b){this.settings.button_width=a;this.settings.button_height=b;var c=this.getMovieElement();if(c!=void 0)c.style.width=a+"px",c.style.height=b+"px";this.callFlash("SetButtonDimensions",[a,b])};SWFUpload.prototype.setButtonText=function(a){this.settings.button_text=a;this.callFlash("SetButtonText",[a])};
SWFUpload.prototype.setButtonTextPadding=function(a,b){this.settings.button_text_top_padding=b;this.settings.button_text_left_padding=a;this.callFlash("SetButtonTextPadding",[a,b])};SWFUpload.prototype.setButtonTextStyle=function(a){this.settings.button_text_style=a;this.callFlash("SetButtonTextStyle",[a])};SWFUpload.prototype.setButtonDisabled=function(a){this.settings.button_disabled=a;this.callFlash("SetButtonDisabled",[a])};
SWFUpload.prototype.setButtonAction=function(a){this.settings.button_action=a;this.callFlash("SetButtonAction",[a])};SWFUpload.prototype.setButtonCursor=function(a){this.settings.button_cursor=a;this.callFlash("SetButtonCursor",[a])};
SWFUpload.prototype.queueEvent=function(a,b){b==void 0?b=[]:b instanceof Array||(b=[b]);var c=this;if(typeof this.settings[a]==="function")this.eventQueue.push(function(){this.settings[a].apply(this,b)}),setTimeout(function(){c.executeNextEvent()},0);else if(this.settings[a]!==null)throw"Event handler "+a+" is unknown or is not a function";};SWFUpload.prototype.executeNextEvent=function(){var a=this.eventQueue?this.eventQueue.shift():null;typeof a==="function"&&a.apply(this)};
SWFUpload.prototype.unescapeFilePostParams=function(a){var b=/[$]([0-9a-f]{4})/i,c={},d;if(a!=void 0){for(var e in a.post)if(a.post.hasOwnProperty(e)){d=e;for(var f;(f=b.exec(d))!==null;)d=d.replace(f[0],String.fromCharCode(parseInt("0x"+f[1],16)));c[d]=a.post[e]}a.post=c}return a};SWFUpload.prototype.testExternalInterface=function(){try{return this.callFlash("TestExternalInterface")}catch(a){return!1}};
SWFUpload.prototype.flashReady=function(){var a=this.getMovieElement();a?(this.cleanUp(a),this.queueEvent("swfupload_loaded_handler")):this.debug("Flash called back ready but the flash movie can't be found.")};
SWFUpload.prototype.cleanUp=function(a){try{if(this.movieElement&&typeof a.CallFunction==="unknown")for(var b in this.debug("Removing Flash functions hooks (this should only run in IE and should prevent memory leaks)"),a)try{typeof a[b]==="function"&&b[0]<="Z"&&(a[b]=null)}catch(c){}}catch(d){}window.__flash__removeCallback=function(a,b){try{a&&(a[b]=null)}catch(c){}}};SWFUpload.prototype.fileDialogStart=function(){this.queueEvent("file_dialog_start_handler")};
SWFUpload.prototype.fileQueued=function(a){a=this.unescapeFilePostParams(a);this.queueEvent("file_queued_handler",a)};SWFUpload.prototype.fileQueueError=function(a,b,c){a=this.unescapeFilePostParams(a);this.queueEvent("file_queue_error_handler",[a,b,c])};SWFUpload.prototype.fileDialogComplete=function(a,b,c){this.queueEvent("file_dialog_complete_handler",[a,b,c])};SWFUpload.prototype.uploadStart=function(a){a=this.unescapeFilePostParams(a);this.queueEvent("return_upload_start_handler",a)};
SWFUpload.prototype.returnUploadStart=function(a){var b;if(typeof this.settings.upload_start_handler==="function")a=this.unescapeFilePostParams(a),b=this.settings.upload_start_handler.call(this,a);else if(this.settings.upload_start_handler!=void 0)throw"upload_start_handler must be a function";b===void 0&&(b=!0);this.callFlash("ReturnUploadStart",[!!b])};SWFUpload.prototype.uploadProgress=function(a,b,c){a=this.unescapeFilePostParams(a);this.queueEvent("upload_progress_handler",[a,b,c])};
SWFUpload.prototype.uploadError=function(a,b,c){a=this.unescapeFilePostParams(a);this.queueEvent("upload_error_handler",[a,b,c])};SWFUpload.prototype.uploadSuccess=function(a,b,c){a=this.unescapeFilePostParams(a);this.queueEvent("upload_success_handler",[a,b,c])};SWFUpload.prototype.uploadComplete=function(a){a=this.unescapeFilePostParams(a);this.queueEvent("upload_complete_handler",a)};SWFUpload.prototype.debug=function(a){this.queueEvent("debug_handler",a)};
SWFUpload.prototype.debugMessage=function(a){if(this.settings.debug){var b=[];if(typeof a==="object"&&typeof a.name==="string"&&typeof a.message==="string"){for(var c in a)a.hasOwnProperty(c)&&b.push(c+": "+a[c]);a=b.join("\n")||"";b=a.split("\n");a="EXCEPTION: "+b.join("\nEXCEPTION: ")}SWFUpload.Console.writeLine(a)}};SWFUpload.Console={};
SWFUpload.Console.writeLine=function(a){var b,c;try{b=document.getElementById("SWFUpload_Console");if(!b)c=document.createElement("form"),document.getElementsByTagName("body")[0].appendChild(c),b=document.createElement("textarea"),b.id="SWFUpload_Console",b.style.fontFamily="monospace",b.setAttribute("wrap","off"),b.wrap="off",b.style.overflow="auto",b.style.width="700px",b.style.height="350px",b.style.margin="5px",c.appendChild(b);b.value+=a+"\n";b.scrollTop=b.scrollHeight-b.clientHeight}catch(d){alert("Exception: "+
d.name+" Message: "+d.message)}};
if(typeof SWFUpload==="function")SWFUpload.queue={},SWFUpload.prototype.initSettings=function(a){return function(){typeof a==="function"&&a.call(this);this.queueSettings={};this.queueSettings.queue_cancelled_flag=!1;this.queueSettings.queue_upload_count=0;this.queueSettings.user_upload_complete_handler=this.settings.upload_complete_handler;this.queueSettings.user_upload_start_handler=this.settings.upload_start_handler;this.settings.upload_complete_handler=SWFUpload.queue.uploadCompleteHandler;this.settings.upload_start_handler=
SWFUpload.queue.uploadStartHandler;this.settings.queue_complete_handler=this.settings.queue_complete_handler||null}}(SWFUpload.prototype.initSettings),SWFUpload.prototype.startUpload=function(a){this.queueSettings.queue_cancelled_flag=!1;this.callFlash("StartUpload",[a])},SWFUpload.prototype.cancelQueue=function(){this.queueSettings.queue_cancelled_flag=!0;this.stopUpload();for(var a=this.getStats();a.files_queued>0;)this.cancelUpload(),a=this.getStats()},SWFUpload.queue.uploadStartHandler=function(a){var b;
typeof this.queueSettings.user_upload_start_handler==="function"&&(b=this.queueSettings.user_upload_start_handler.call(this,a));b=b===!1?!1:!0;this.queueSettings.queue_cancelled_flag=!b;return b},SWFUpload.queue.uploadCompleteHandler=function(a){var b=this.queueSettings.user_upload_complete_handler;a.filestatus===SWFUpload.FILE_STATUS.COMPLETE&&this.queueSettings.queue_upload_count++;if(typeof b==="function"?b.call(this,a)!==!1:a.filestatus!==SWFUpload.FILE_STATUS.QUEUED)this.getStats().files_queued>
0&&this.queueSettings.queue_cancelled_flag===!1?this.startUpload():(this.queueSettings.queue_cancelled_flag===!1?this.queueEvent("queue_complete_handler",[this.queueSettings.queue_upload_count]):this.queueSettings.queue_cancelled_flag=!1,this.queueSettings.queue_upload_count=0)};function fileQueued(a){try{var b=new FileProgress(a,this.customSettings.progressTarget);b.setStatus("Pending...");b.toggleCancel(!0,this)}catch(c){this.debug(c)}}
function fileQueueError(a,b,c){try{if(b===SWFUpload.QUEUE_ERROR.QUEUE_LIMIT_EXCEEDED)alert("You have attempted to queue too many files.\n"+(c===0?"You have reached the upload limit.":"You may select "+(c>1?"up to "+c+" files.":"one file.")));else{var d=new FileProgress(a,this.customSettings.progressTarget);d.setError();d.toggleCancel(!1);switch(b){case SWFUpload.QUEUE_ERROR.FILE_EXCEEDS_SIZE_LIMIT:d.setStatus("File is too big.");this.debug("Error Code: File too big, File name: "+a.name+", File size: "+
a.size+", Message: "+c);break;case SWFUpload.QUEUE_ERROR.ZERO_BYTE_FILE:d.setStatus("Cannot upload Zero Byte files.");this.debug("Error Code: Zero byte file, File name: "+a.name+", File size: "+a.size+", Message: "+c);break;case SWFUpload.QUEUE_ERROR.INVALID_FILETYPE:d.setStatus("Invalid File Type.");this.debug("Error Code: Invalid File Type, File name: "+a.name+", File size: "+a.size+", Message: "+c);break;default:a!==null&&d.setStatus("Unhandled Error"),this.debug("Error Code: "+b+", File name: "+
a.name+", File size: "+a.size+", Message: "+c)}}}catch(e){this.debug(e)}}function fileDialogComplete(a){try{if(a>0&&(btn=document.getElementById(this.customSettings.cancelButtonId)))btn.disabled=!1;this.startUpload()}catch(b){this.debug(b)}}
function uploadStart(a){try{var b=new FileProgress(a,this.customSettings.progressTarget);b.setStatus("Uploading...");b.toggleCancel(!0,this)}catch(c){}window.onbeforeunload=function(){return"Your upload has not completed yet. Press CANCEL to remain on this page and let your upload finish."};return!0}function uploadProgress(a,b,c){try{var d=Math.ceil(b/c*100),e=new FileProgress(a,this.customSettings.progressTarget);e.setProgress(d);e.setStatus("Uploading...")}catch(f){this.debug(f)}}
function uploadSuccess(a){try{var b=new FileProgress(a,this.customSettings.progressTarget);b.setComplete();b.setStatus("Complete.");b.toggleCancel(!1)}catch(c){}}
function uploadError(a,b,c){try{var d=new FileProgress(a,this.customSettings.progressTarget);d.setError();d.toggleCancel(!1);switch(b){case SWFUpload.UPLOAD_ERROR.HTTP_ERROR:d.setStatus("Upload Error: "+c);this.debug("Error Code: HTTP Error, File name: "+a.name+", Message: "+c);break;case SWFUpload.UPLOAD_ERROR.UPLOAD_FAILED:d.setStatus("Upload Failed.");this.debug("Error Code: Upload Failed, File name: "+a.name+", File size: "+a.size+", Message: "+c);break;case SWFUpload.UPLOAD_ERROR.IO_ERROR:d.setStatus("Server (IO) Error");
this.debug("Error Code: IO Error, File name: "+a.name+", Message: "+c);break;case SWFUpload.UPLOAD_ERROR.SECURITY_ERROR:d.setStatus("Security Error");this.debug("Error Code: Security Error, File name: "+a.name+", Message: "+c);break;case SWFUpload.UPLOAD_ERROR.UPLOAD_LIMIT_EXCEEDED:d.setStatus("Upload limit exceeded.");this.debug("Error Code: Upload Limit Exceeded, File name: "+a.name+", File size: "+a.size+", Message: "+c);break;case SWFUpload.UPLOAD_ERROR.FILE_VALIDATION_FAILED:d.setStatus("Failed Validation.  Upload skipped.");
this.debug("Error Code: File Validation Failed, File name: "+a.name+", File size: "+a.size+", Message: "+c);break;case SWFUpload.UPLOAD_ERROR.FILE_CANCELLED:if(this.getStats().files_queued===0&&(btn=document.getElementById(this.customSettings.cancelButtonId)))btn.disabled=!0;d.setStatus("Cancelled");d.setCancelled();break;case SWFUpload.UPLOAD_ERROR.UPLOAD_STOPPED:d.setStatus("Stopped");break;default:d.setStatus("Unhandled Error: "+b),this.debug("Error Code: "+b+", File name: "+a.name+", File size: "+
a.size+", Message: "+c)}}catch(e){this.debug(e)}}function uploadComplete(){if(this.getStats().files_queued===0){if(btn=document.getElementById(this.customSettings.cancelButtonId))btn.disabled=!0;window.onbeforeunload=null}}
function FileProgress(a,b){this.fileProgressID=a.id;this.opacity=100;this.height=0;if(this.fileProgressWrapper=document.getElementById(this.fileProgressID))this.fileProgressElement=this.fileProgressWrapper.firstChild;else{this.fileProgressWrapper=document.createElement("div");this.fileProgressWrapper.className="progressWrapper";this.fileProgressWrapper.id=this.fileProgressID;this.fileProgressElement=document.createElement("div");this.fileProgressElement.className="progressContainer";var c=document.createElement("a");
c.className="progressCancel";c.href="#";c.style.visibility="hidden";c.appendChild(document.createTextNode(" "));var d=document.createElement("div");d.className="progressName";d.appendChild(document.createTextNode(a.name));var e=document.createElement("div");e.className="progressBar";var f=document.createElement("div");f.className="progressBarInProgress";f.style.width="0%";var g=document.createElement("a");g.className="closer";g.innerHTML="[hide]";g.style.display="none";$(g).click(function(){$(this.parentNode).slideUp();
return!1});var i=document.createElement("div");i.className="progressBarStatus";i.innerHTML=" ";this.fileProgressElement.appendChild(c);this.fileProgressElement.appendChild(d);this.fileProgressElement.appendChild(g);this.fileProgressElement.appendChild(i);e.appendChild(f);this.fileProgressElement.appendChild(e);this.fileProgressWrapper.appendChild(this.fileProgressElement);document.getElementById(b).appendChild(this.fileProgressWrapper)}this.height=this.fileProgressWrapper.offsetHeight}
FileProgress.prototype.setProgress=function(a){this.fileProgressElement.className="progressContainer green";this.fileProgressElement.childNodes[4].childNodes[0].className="progressBarInProgress";this.fileProgressElement.childNodes[4].childNodes[0].style.width=a+"%"};
FileProgress.prototype.setComplete=function(){this.fileProgressElement.className="progressContainer blue";this.fileProgressElement.childNodes[4].childNodes[0].className="progressBarComplete";this.fileProgressElement.childNodes[4].childNodes[0].style.width="";this.showCloser()};
FileProgress.prototype.setError=function(){this.fileProgressElement.className="progressContainer red";this.fileProgressElement.childNodes[4].childNodes[0].className="progressBarError";this.fileProgressElement.childNodes[4].childNodes[0].style.width="";this.showCloser()};
FileProgress.prototype.setCancelled=function(){this.fileProgressElement.className="progressContainer";this.fileProgressElement.childNodes[4].childNodes[0].className="progressBarError";this.fileProgressElement.childNodes[4].childNodes[0].style.width="";this.showCloser()};FileProgress.prototype.setStatus=function(a){this.fileProgressElement.childNodes[3].innerHTML=a};FileProgress.prototype.showCloser=function(){this.fileProgressElement.childNodes[2].style.display="inline"};
FileProgress.prototype.toggleCancel=function(a,b){this.fileProgressElement.childNodes[0].style.visibility=a?"visible":"hidden";if(b){var c=this.fileProgressID;this.fileProgressElement.childNodes[0].onclick=function(){b.cancelUpload(c);return!1}}};
function ksr_swfupload_settings(a,b,c,d,e){var f={upload_url:a.attr("url"),flash_url:"/swf/swfupload.swf",post_params:{authenticity_token:$("meta[name='csrf-token']").attr("content"),_method:a.attr("method")||"post",last_page:window.location.pathname},file_post_name:a.attr("name"),debug:!1};if(e)f.post_params=a.data("params")||{};if(!e)f.upload_url=f.upload_url+"?_ksr_session="+encodeURIComponent(readCookie("_ksr_session"));b?f.button_action=SWFUpload.BUTTON_ACTION.SELECT_FILES:(f.file_queue_limit=
1,f.button_action=SWFUpload.BUTTON_ACTION.SELECT_FILE);if(!c)f.button_image_url="/images/media/swfupload_button.png",f.button_width="140",f.button_height="35",f.button_text_style=".text { color: #ffffff; font-weight: bold; text-align: center; font-size: 15px; font-family: Helvetica,Arial,sans-serif; }",f.button_placeholder_id="spanButtonPlaceHolder",f.button_text='<span class="text">Upload</span>',f.button_window_mode=SWFUpload.WINDOW_MODE.OPAQUE,f.button_text_top_padding=6;d||$.extend(f,{file_queued_handler:fileQueued,
file_queue_error_handler:fileQueueError,file_dialog_complete_handler:fileDialogComplete,upload_start_handler:uploadStart,upload_progress_handler:uploadProgress,upload_success_handler:uploadSuccess,upload_error_handler:uploadError,upload_complete_handler:uploadComplete,debug_handler:function(a){$.console.log(a)},custom_settings:{cancelButtonId:"btnCancel",progressTarget:"upload-progress"}});return f}window.ksr_swfupload_settings=ksr_swfupload_settings;
$(".edit_post .media").livequery(function(){var a=jQuery(this),b=a.find(".swfu .video"),c=ksr_swfupload_settings(b),d=a.find(".swfu .sounds"),e=ksr_swfupload_settings(d,!0),f=a.find(".swfu .images"),g=ksr_swfupload_settings(f,!0),i,j,h;c.button_image_url="/images/media/add_video.png";c.button_width="106";c.button_height="29";c.button_text="";c.button_placeholder_id="video-button-placeholder";c.upload_success_handler=function(b,c){a.find(".attached .video").remove();a.find(".attached").append(c);return uploadSuccess.call(this,
b,c)};c.file_size_limit="250MB";c.file_types="*.avi;*.dv;*.mov;*.qt;*.mpeg;*.mpg;*.mp4;*.3gp;*.asf;*.wmv;*.flv;";c.file_types_description="Video Files";e.button_image_url="/images/media/add_audio.png";e.button_width="106";e.button_height="29";e.button_text="";e.button_placeholder_id="audios-button-placeholder";e.upload_success_handler=function(b,c){a.find(".attached").append(c);return uploadSuccess.call(this,b,c)};e.file_size_limit="10MB";e.file_types="*.mp3;*.mp4;*.m4a;*.aac;";e.file_types_description=
"Audio Files";g.button_image_url="/images/media/add_photo.png";g.button_width="106";g.button_height="29";g.button_text="";g.button_placeholder_id="images-button-placeholder";g.upload_success_handler=function(b,c){a.find(".attached").append(c);return uploadSuccess.call(this,b,c)};g.file_size_limit="10MB";g.file_types="*.gif;*.jpg;*.jpeg;*.png;*.bmp";g.file_types_description="Image Files";a.find(".swfu").append('<span id="video-button-placeholder"></span><span id="audios-button-placeholder"></span><span id="images-button-placeholder"></span>');
a.find(".swfu").after('<div id="upload-progress"></div>');i=new SWFUpload(c);j=new SWFUpload(e);h=new SWFUpload(g);a.find("#btnCancel").bind("click",function(){i.cancelQueue();j.cancelQueue();h.cancelQueue()});b.remove();d.remove();f.remove()});
function clickjack(a){return{button_width:a.outerWidth(),button_height:a.outerHeight(),button_placeholder_id:"spanButtonPlaceHolder",button_window_mode:SWFUpload.WINDOW_MODE.TRANSPARENT,button_cursor:SWFUpload.CURSOR.HAND,button_image_url:"/images/transparent1.gif"}}
(function(){$.fn.ksr_file_upload=function(a){function b(b,d){return $.pollster(b,function(b){if(b.image_src)return d.find(".success img.preview").attr("src",b.image_src).removeAttr("data-status_url"),d.removeClass("encoding"),a.after_encode&&a.after_encode(),!0;return!1})}a=a||{};return $(this).each(function(){function c(a){p=a;f.data("uploading",a)}function d(a,d){var e=d,g=k.find(".success");typeof e==="string"&&(e=$.parseJSON(e)||{});c(!1);e.image_src&&g.find("img.preview").attr("src",e.image_src);
e.status_url&&(l=b(e.status_url,o));m.attr("data-status_url",e.status_url);f.trigger("file_added",[e])}function e(a){$.ajax({url:f.data("videoUrl"),data:{remote_upload:!0,file_name:encodeURIComponent(a.name),file_size:a.size},type:"POST",success:function(b){d(a,b)},error:function(a){k.trigger("ksr_file_upload:reset");c(!1);growl({error:"Could not upload this file. "+a.responseText})}})}var f=$(this),g=RegExp(window.location.host+"|^/"),i=!f.attr("url").match(g),j=f.siblings(".progress"),h=f.parent(),
o=h.parent();g=ksr_swfupload_settings(f,!1,!0,!0,i);var k=f.closest("form"),m=o.find(".success img.preview"),l,p=!1,n;f.hide();f.siblings("label").hide();$.extend(g,clickjack(h));if(a.type)if(a.type==="video")g.file_size_limit="1GB",g.file_types="*.avi;*.dv;*.mov;*.qt;*.mpeg;*.mpg;*.mp4;*.3gp;*.asf;*.wmv;*.flv;";else if(a.type==="audio")g.file_size_limit="10MB",g.file_types="*.mp3;*.mp4;*.m4a;*.aac;";else if(a.type==="image")g.file_size_limit="10MB",g.file_types="*.gif;*.jpg;*.jpeg;*.png;*.bmp";g.file_queued_handler=
function(){l&&l.stop();n.startUpload();c(!0);j.removeClass("finished");f.trigger("file_queued");window.onbeforeunload=function(){if(p)return'Your upload has not completed yet. Click "Stay on Page" to let your upload finish. Click "Leave Page" to abandon your upload.'}};g.file_queue_error_handler=function(a,b,d){k.trigger("ksr_file_upload:reset");c(!1);growl({error:"Could not upload this file. "+d})};g.upload_progress_handler=function(a,b,c){a=Math.round(b/c*100);j.find(".bar").css("width",a+"%");
j.find(".percentage").text(a+"%");a===100&&(j.addClass("finished"),j.find(".percentage").text("Processing..."),k.find("input[type=submit]").val("Processing, please wait..."))};g.upload_success_handler=function(a,b,c){i?e(a,b,c):d(a,b,c)};g.upload_error_handler=function(a,b,d){$.console.log("Error file:",a,b,d);k.trigger("ksr_file_upload:reset");c(!1);growl({error:"There was an error with this file. Please try a different file."});f.trigger("error")};i||$.extend(g.post_params,{new_style:!0});m.data("status_url")&&
(l=b(m.data("status_url"),o),m.removeAttr("status_url"));h.prepend('<span id="spanButtonPlaceHolder"></span>');h.bind("pollster:stop",function(){l&&l.stop()});h.bind("ksr_file_upload:cancel cancel",function(){n.cancelUpload(void 0,!1);k.trigger("ksr_file_upload:reset");f.trigger("error");c(!1)});h.bind("destroy",function(){h.trigger("ksr_file_upload:cancel");n.destroy()});h.bind("resize",function(){h.find("object").attr("width",h.outerWidth()).attr("height",h.outerHeight())});n=new SWFUpload(g)})}})();
$(".edit_user input.avatar").livequery(function(){var a=jQuery(this),b=ksr_swfupload_settings(a);b.upload_success_handler=function(b,d){a.siblings(".upload").remove();a.before(d);return uploadSuccess.call(this,b,d)};b.file_size_limit="10MB";b.file_types="*.gif;*.jpg;*.jpeg;*.png";b.file_types_description="Image Files";a.after('<div id="upload-progress"></div>');a.after('<span id="spanButtonPlaceHolder"></span>');new SWFUpload(b);a.hide()});
(function set_up_curated_page_upload(){var b=$(".published .add_photo_button, .header .image.value:visible",$("#curated_pages_show")),c,d,e,f;if(b.length)c=$("#curated_pages_show .header .image.value"),d=c.find(".progress"),e=ksr_swfupload_settings(c.siblings("input"),!1,!0,!0),$.extend(e,clickjack(b)),e.file_queued_handler=function(){f.startUpload();c.show();d.show();c.find("img").hide();d.removeClass("finished");b.is(".add_photo_button")&&(b.css("visibility","hidden"),b.closest(".header").removeClass("without_photo").addClass("with_photo"))},
e.upload_progress_handler=function(b,c,e){b=Math.round(c/e*100);d.find(".bar").css("width",b+"%");d.find(".percentage").text(b+"%");b===100&&(d.addClass("finished"),d.find(".percentage").text(""))},e.upload_success_handler=function(e,f){d.hide();c.find("img").attr("src",f);c.find("img").show();c.closest(".header").removeClass("without_photo").addClass("with_photo");d.find(".percentage").text("0%");b.is(".add_photo_button")&&(b.remove(),set_up_curated_page_upload())},e.upload_error_handler=function(){d.hide();
c.find("img").show();b.is(".add_photo_button")&&(c.hide(),b.css("visibility","visible"),b.closest(".header").removeClass("with_photo").addClass("without_photo"))},b.prepend('<span id="spanButtonPlaceHolder"></span>'),f=new SWFUpload(e)})();
$(document).bind("wym_file_upload_added",function(a){a=$(a.target);var b=a.closest("form");a.ksr_file_upload();a.bind("file_queued",function(){b.find(".url_fields, .embed").hide();b.find(".credit_and_caption").slideDown().length?b.find(".or_copy").text("Optional").width("80px"):b.find("hr.or, .or_copy").hide();b.find("input[type=submit]").val("Uploading, please wait...")})});
