<?php 
//
// This source code was recovered by Recover-PHP.com
//


class Setting extends SettingsAppModel
{
    public $name = "Setting";
    public $actsAs = array( "Containable", "MultiValidatable", "Search.Searchable" );
    public $validate = array( "fromemail" => array( "rule" => array( "email", true ), "message" => "please enter email address" ), "facebook_lnk" => array( "rule" => array( "url", true ), "message" => "please enter only facebook url" ), "twitter_lnk" => array( "rule" => array( "url", true ), "message" => "please enter only twitter url" ), "meet_team" => array( "rule" => array( "url", true ), "message" => "please enter only meet team url" ), "work_with_us" => array( "rule" => array( "url", true ), "message" => "please enter only work with us url" ), "fromname" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter from name", "last" => true ), "reply_to_email" => array( "reply_to_email1" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter email address", "last" => true ), "reply_to_email2" => array( "rule" => "email", "message" => "please enter valid email address" ) ), "staffemail" => array( "rule" => "email", "message" => "please enter valid email address" ), "meta_description" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter meta description" ), "meta_keywords" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter meta keyword" ), "site_title" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter site title", "allowEmpty" => false ), "email" => array( "email1" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter email address", "last" => true ), "email2" => array( "rule" => "email", "message" => "please enter valid email address" ) ), "postal_address" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter postal address" ), "newsletter" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter newsletter listing limit" ), "project_comment" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter project comment listing limit" ), "project_listing" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter project listing limit" ), "project_update" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter project update listing limit" ), "project_backers" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter project backers listing limit" ), "blog_listing" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter blog listing limit" ), "blog_comments" => array( "rule" => "notEmpty", "required" => true, "message" => "Please enter blog comment listing limit" ) );

}
